### ISSUE TITLE
Launching of script direct after Zotero

### ISSUE THREAD

**Issue by LightTemplar** [jcuenod/zotero-backup-scripts#2]
Launching of the backup script on time has risk, that Zotero will be running at time and SQLite database file will be corrupt by backup. This is the main problem, why we can't sync it with nextcloud etc. 
So I find the solution to add launching of the backup script into the Zotero link itself, like /path/to/zotero && /database/dir/backup.sh
Works like charm!

**Comment by jcuenod** [comment]
I have not tested this, but my understanding is that this approach backs up the journal files created by sqlite. If you restore from a backup that includes journal files, sqlite will reconcile the journal files before providing access to the database. This will prevent the database from becoming corrupt.
