### ISSUE TITLE
Extension list for git comment

### ISSUE THREAD

**Issue by LightTemplar** [jcuenod/zotero-backup-scripts#3]
Could you please help with adding another extensions into backup.sh for commenting of commits in git?

**Comment by jcuenod** [comment]
What do you need help with?

**Comment by LightTemplar** [comment]
I have also .html, .epub, .pptx and .docx files in Zotero and would like to trace them in commit comments too.

**Comment by jcuenod** [comment]
Great idea.  6ebe89a
